#!/usr/bin/env python

import sys
import os
import subprocess
import sipconfig

# The name of the SIP build file generated by SIP and used by the build
# system.
build_file = "siteshotgun.sbf"

# Get the SIP configuration information.
config = sipconfig.Configuration()

# Work around sipconfig module bug on OS X
config.qt_framework = None

# Run SIP to generate the code.
sipcmd = [config.sip_bin]
sipcmd.extend(["-I", "../../../plugins/python/sip/"]) # For finding _shotgun.sip
sipcmd.extend(["-b", "src/%s" % build_file])
sipcmd.extend(["-c", "src"])
sipcmd.append("-e")
sipcmd.append("-w")
sipcmd.append("sip/_siteshotgun.sip")
print " ".join(sipcmd)
result = subprocess.call(sipcmd)
if result != 0:
    sys.exit(result)

# Create the Makefile.
makefile = sipconfig.SIPModuleMakefile(config, build_file, dir="src")

try:
    xmlrpc_cppflags = os.environ["XMLRPC_CFLAGS"]
    xmlrpc_ldflags = os.environ["XMLRPC_LDFLAGS"]
    xmlrpc_ldadd = os.environ["XMLRPC_LDADD"]
    xmlrpc_libs = xmlrpc_ldadd.replace("-l", "")
    automake_defs = os.environ["DEFS"]
except KeyError:
    print "./configure.py is intended to be run by make."
    sys.exit(1)

makefile.extra_cxxflags = [automake_defs, xmlrpc_cppflags]
makefile.extra_lflags = [xmlrpc_ldflags]

makefile.extra_include_dirs = ["../../../lib", "../../../../lib"]
makefile.extra_lib_dirs = ["../../../lib/SiteShotgun/.libs",
                           "../../../../lib/Shotgun/.libs"]
makefile.extra_libs = ["SiteShotgun", "Shotgun", xmlrpc_libs, "stdc++"]

# Generate the Makefile itself.
makefile.generate()
