#!/usr/bin/env python

import os
import subprocess
import sipconfig

# The name of the SIP build file generated by SIP and used by the build
# system.
build_file = "shotgun.sbf"

# Get the SIP configuration information.
config = sipconfig.Configuration()

# Run SIP to generate the code.
sipcmd = ["sip"]
sipcmd.extend(["-I", "../../../lib/"])
sipcmd.extend(["-b", "src/%s" % build_file])
sipcmd.extend(["-c", "src"])
sipcmd.append("-e")
sipcmd.append("-w")
sipcmd.append("sip/_shotgun.sip")
subprocess.call(sipcmd)

# Create the Makefile.
makefile = sipconfig.SIPModuleMakefile(config, build_file, dir="src")

xmlrpc_cppflags = os.environ.get("XMLRPC_CFLAGS", None)
xmlrpc_ldflags = os.environ.get("XMLRPC_LDFLAGS", None)
xmlrpc_ldadd = os.environ.get("XMLRPC_LDADD", None)

if (xmlrpc_cppflags is None
    or xmlrpc_ldflags is None
    or xmlrpc_ldadd is None):
    print "./configure.py is intended to be run by make."

makefile.extra_cxxflags = [xmlrpc_cppflags]
makefile.extra_lflags = ["-Wl,-Bstatic", "-lShotgun", "-Wl,-Bdynamic",
                          xmlrpc_ldflags, xmlrpc_ldadd, "-lstdc++"]

makefile.extra_include_dirs = ["../../../lib"]
makefile.extra_lib_dirs = ["../../../lib/Shotgun/.libs"]

# Generate the Makefile itself.
makefile.generate()
