#!/usr/bin/env python

import os
import subprocess
import sipconfig

# The name of the SIP build file generated by SIP and used by the build
# system.
build_file = "shotgun.sbf"

# Get the SIP configuration information.
config = sipconfig.Configuration()

# Run SIP to generate the code.
sipcmd = ["sip"]
sipcmd.extend(["-I", "../../../lib/"])
sipcmd.extend(["-b", "src/%s" % build_file])
sipcmd.extend(["-c", "src"])
sipcmd.append("-e")
sipcmd.append("-w")
sipcmd.append("sip/_shotgun.sip")
subprocess.call(sipcmd)

# Create the Makefile.
makefile = sipconfig.SIPModuleMakefile(config, build_file, dir="src")

xmlrpc_cppflags = subprocess.Popen(["xmlrpc-c-config", "c++2", "client", "--cflags"], 
                                    stdout=subprocess.PIPE).communicate()[0].strip()
xmlrpc_ldflags = subprocess.Popen(["xmlrpc-c-config", "c++2", "client", "--ldflags"], 
                                   stdout=subprocess.PIPE).communicate()[0].strip()
xmlrpc_ldadd = subprocess.Popen(["xmlrpc-c-config", "c++2", "client", "--ldadd"], 
                                  stdout=subprocess.PIPE).communicate()[0].strip()

makefile.extra_cxxflags = [xmlrpc_cppflags]
makefile.extra_lflags = ["-lShotgun", xmlrpc_ldadd, "-lstdc++"]

makefile.extra_include_dirs = ["../../../lib"]
makefile.extra_lib_dirs = ["../../../lib/Shotgun/.libs"]

# Generate the Makefile itself.
makefile.generate()
