#!/usr/bin/env python

import os
import subprocess
import sipconfig

# The name of the SIP build file generated by SIP and used by the build
# system.
build_file = "shotgun.sbf"

# Get the SIP configuration information.
config = sipconfig.Configuration()

# Run SIP to generate the code.
sipcmd = ["sip"]
sipcmd.extend(["-I", "../../../lib/"])
sipcmd.extend(["-b", "src/%s" % build_file])
sipcmd.extend(["-c", "src"])
sipcmd.append("-e")
sipcmd.append("-w")
sipcmd.append("sip/_shotgun.sip")
subprocess.call(sipcmd)

# Create the Makefile.
makefile = sipconfig.SIPModuleMakefile(config, build_file, dir="src")

# Add the library we are wrapping.  The name doesn't include any platform
# specific prefixes or extensions (e.g. the "lib" prefix on UNIX, or the
# ".dll" extension on Windows).
makefile.extra_libs = ["Shotgun"]
makefile.extra_include_dirs = ["../../../lib"]
makefile.extra_lib_dirs = ["../../../lib/Shotgun/.libs"]
# Generate the Makefile itself.
makefile.generate()
